/** Public, browser-safe policy. No store identity or credential is built in. */
export interface AnalyticsConfig {
  shop: { shopId: string; storefrontId: string; myshopifyDomain: string };
  i18n: { country: string; language: string; currency: string };
  origins: string[];
  publicPaths: string[];
  productPathPrefix: string;
  experimentalEvents: boolean;
}

export const ANALYTICS_PACKAGE_VERSION = "2026.10.0-preview.4";
export const ANALYTICS_ENDPOINT = "https://monorail-edge.shopifysvc.com/unstable/produce_batch";
export const PRIVATE_ANALYTICS_HEADERS = {
  "cache-control": "private, no-store, max-age=0",
  "cdn-cache-control": "no-store",
  "surrogate-control": "no-store",
  vary: "Cookie, Origin",
};

export function publicAnalyticsUrl(value: string, origin: string, paths: readonly string[]): string | null {
  try {
    const url = new URL(value, origin);
    if (url.origin !== origin || url.username || url.password || !paths.includes(url.pathname)) return null;
    return `${url.origin}${url.pathname}`;
  } catch { return null; }
}

/** Only the exact bounded operation generated by the pinned Customer Privacy API. */
export function analyticsConsentQuery(body: unknown): string | null {
  if (!body || typeof body !== "object") return null;
  const b = body as { query?: unknown; variables?: unknown };
  if (typeof b.query !== "string" || b.query.length > 4096 ||
      (b.variables && (typeof b.variables !== "object" || Object.keys(b.variables).length))) return null;
  const match = b.query.match(/^query\s*\{\s*consentManagement\s*\{\s*cookies\s*\(\s*visitorConsent\s*:\s*\{([^{}]*)\}(?:\s*,\s*(?:origReferrer|landingPage)\s*:\s*"(?:\\.|[^"\\])*")*\s*\)\s*\{\s*trackingConsentCookie\s+cookieDomain\s+landingPageCookie\s+origReferrerCookie\s+shopifyUnique\s+shopifyVisit\s*\}\s*customerAccountUrl\s*\}\s*\}\s*$/);
  if (!match) return null;
  const purposes = new Map<string, string>();
  for (const field of match[1].split(",").map(v => v.trim()).filter(Boolean)) {
    const part = field.match(/^(analytics|marketing|preferences|saleOfData)\s*:\s*(true|false)$/);
    if (!part || purposes.has(part[1])) return null;
    purposes.set(part[1], part[2]);
  }
  if (purposes.size !== 0 && purposes.size !== 4) return null;
  // This step enables statistics only, even when an external banner asks for more.
  if (purposes.size) for (const key of ["marketing", "preferences", "saleOfData"]) purposes.set(key, "false");
  const choice = [...purposes].map(([key, value]) => `${key}:${value}`).join(",");
  return `query { consentManagement { cookies(visitorConsent:{${choice}},origReferrer:"",landingPage:"/") { trackingConsentCookie cookieDomain landingPageCookie origReferrerCookie shopifyUnique shopifyVisit } customerAccountUrl } }`;
}

const PAGE_FIELDS = new Set(["source", "api_client_id", "asset_version_id", "hydrogenSubchannelId", "is_persistent_cookie", "deprecated_visit_token", "unique_token", "event_time", "event_id", "event_source_url", "referrer", "user_agent", "navigation_type", "navigation_api", "shop_id", "currency", "ccpa_enforced", "gdpr_enforced", "gdpr_enforced_as_string", "analytics_allowed", "marketing_allowed", "sale_of_data_allowed", "event_name", "canonical_url", "customer_id"]);
const PRODUCT_FIELDS = new Set(["product_gid", "variant_gid", "product_id", "variant_id", "name", "variant", "brand", "category", "price", "quantity", "sku"]);
const timing = (value: Record<string, unknown> = {}) => Object.fromEntries(Object.entries(value).filter(([key, n]) =>
  ["event_created_at_ms", "event_sent_at_ms"].includes(key) && typeof n === "number" && Number.isFinite(n)));

/** The CDN sender reads ambient URLs: filter again at the final transport boundary. */
export function sanitizeAnalyticsBatch(body: string, origin: string, config: AnalyticsConfig, paths: readonly string[]): string | null {
  try {
    const batch = JSON.parse(body);
    if (!Array.isArray(batch.events) || !batch.events.length || batch.events.length > 10) return null;
    const events = [];
    for (const event of batch.events) {
      const p = event.payload;
      const extension = config.experimentalEvents && ["product_page_rendered", "product_added_to_cart"].includes(p?.event_name);
      if (event.schema_id !== "custom_storefront_customer_tracking/1.2" ||
          (p?.event_name !== "page_rendered" && !extension) || p.source !== "headless" ||
          p.api_client_id !== 12875497473 || String(p.shop_id) !== config.shop.shopId ||
          p.hydrogenSubchannelId !== "0" || p.analytics_allowed !== true) return null;
      const url = publicAnalyticsUrl(p.event_source_url, origin, paths);
      if (!url) return null;
      const payload: Record<string, unknown> = Object.fromEntries(Object.entries(p).filter(([key, value]) =>
        PAGE_FIELDS.has(key) && (typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value)) ||
          (typeof value === "string" && value.length <= 2048))));
      Object.assign(payload, { event_source_url: url, canonical_url: url, referrer: "", customer_id: 0,
        marketing_allowed: false, sale_of_data_allowed: false });
      if (extension) {
        if (Array.isArray(p.products)) payload.products = p.products.slice(0, 100).map((raw: string) => {
          const product = JSON.parse(raw);
          return JSON.stringify(Object.fromEntries(Object.entries(product).filter(([key, value]) => PRODUCT_FIELDS.has(key) &&
            ((typeof value === "string" && value.length <= 512) || (typeof value === "number" && Number.isFinite(value))))));
        });
        if (typeof p.total_value === "number" && Number.isFinite(p.total_value)) payload.total_value = p.total_value;
        if (typeof p.cart_token === "string") payload.cart_token = p.cart_token.split(/[?#]/)[0].slice(0, 256);
      }
      events.push({ schema_id: event.schema_id, payload, metadata: timing(event.metadata) });
    }
    return JSON.stringify({ events, metadata: timing(batch.metadata) });
  } catch { return null; }
}
